# Don't allow new windows to be larger than the screen
autofit-larger=100%x100%

# enable hw decoding if available
hwdec=yes

# save play position to watch later dir (~/.local/state/mpv)
save-position-on-quit=yes
