fallback = ''
separator = ' '

[matching]
'discord' = ''
'com.discordapp.Discord' = ''
'balena-etcher' = ''
'steam' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Google-chrome' = ''
'google-chrome' = ''
'Chromium' = ''
'io.github.ungoogled_software.ungoogled_chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = '' # lmao this is the vimeo icon
'/vim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'kitty' = ''
'org.kde.dolphin' = ''
'thunar' = ''
