# BEGIN_KITTY_FONTS
font_family      family="Atkinson Hyperlegible Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 10.0 

# make cursor a blinking block
cursor_shape block
cursor_blink_interval -1
# don't let the shell change the cursor to a bar
shell_integration no-cursor

# disable both audio and visual bell always
enable_audio_bell no
visual_bell_duration 0.0

# do not show title bar or scroll bar
hide_window_decorations yes

# patch Nerd Font symbols into current font
include patch-nerd-symbols.conf
