#!/usr/bin/env fish

function _usage
  echo "Usage: niri-interactive-rename-workspace [-h | --help] [NAME]"
end

function _debug
  echo "Debug: $argv" >&2
end

# flags
argparse 'h/help' -- $argv
or { _usage; return 1 }
if set -ql _flag_help
  _usage
  return 0
end

# max 1 arg
argparse --max-args 1 -- $argv
or { _usage; return 1 }

if set -q argv[1]
  set input_method "argv"
  _debug "accepting input from argv"
  set name "$argv[1]"
  _debug "new workspace name is '$name'"
else
  set input_method "gui"
  _debug "accepting input from gui"
  set old (niri msg workspaces | grep '*' | cut -d' ' -f4 | tr -d '"')
  _debug "old workspace name is '$old'"
  set name (fuzzel --dmenu --mesg="New workspace name?" --prompt-only="> " --search="$old")
  set fuzzel_status $status
  _debug "new workspace name is '$name', with return status $fuzzel_status"
end

if test $input_method = "argv"; or test $fuzzel_status -eq 0
  # change name if there were no errors
  if test -z "$name"
    _debug "clearing workspace name"
    niri msg action unset-workspace-name
  else
    _debug "setting workspace name to '$name'"
    niri msg action set-workspace-name "$name"
  end
else
  # log if there was an error with fuzzel
  _debug "not setting workspace name"
end
