[mgr]
# prepend will overwrite any present keymaps
prepend_keymap = [
  # directories alongside files
 	{ on = [ "<", "m" ], run = [ "sort mtime --dir-first=no --reverse=no", "linemode mtime" ],  desc = "sort: mtime" },
	{ on = [ "<", "M" ], run = [ "sort mtime --dir-first=no --reverse", "linemode mtime" ],     desc = "rsort: mtime" },
	{ on = [ "<", "b" ], run = [ "sort btime --dir-first=no --reverse=no", "linemode btime" ],  desc = "sort: btime" },
	{ on = [ "<", "B" ], run = [ "sort btime --dir-first=no --reverse", "linemode btime" ],     desc = "rsort: btime" },
	{ on = [ "<", "e" ], run = "sort extension --dir-first=no --reverse=no",                    desc = "sort: ext" },
	{ on = [ "<", "E" ], run = "sort extension --dir-first=no --reverse",                       desc = "rsort: ext" },
	{ on = [ "<", "a" ], run = "sort alphabetical --dir-first=no --reverse=no",                 desc = "sort: alpha" },
	{ on = [ "<", "A" ], run = "sort alphabetical --dir-first=no --reverse",                    desc = "rsort: alpha" },
	{ on = [ "<", "n" ], run = "sort natural --dir-first=no --reverse=no",                      desc = "sort: natural" },
	{ on = [ "<", "N" ], run = "sort natural --dir-first=no --reverse",                         desc = "rsort: natural" },
	{ on = [ "<", "s" ], run = [ "sort size --dir-first=no --reverse=no", "linemode size" ],    desc = "sort: size" },
	{ on = [ "<", "S" ], run = [ "sort size --dir-first=no --reverse", "linemode size" ],       desc = "rsort: size" },
	{ on = [ "<", "r" ], run = "sort random --dir-first=no --reverse=no",                       desc = "sort: rand" },
  # directories before files
  # (overwrite defaults to add --dir-first=yes)
 	{ on = [ ",", "m" ], run = [ "sort mtime --dir-first=yes --reverse=no", "linemode mtime" ],  desc = "sort: mtime (dirfirst)" },
	{ on = [ ",", "M" ], run = [ "sort mtime --dir-first=yes --reverse", "linemode mtime" ],     desc = "rsort: mtime (dirfirst)" },
	{ on = [ ",", "b" ], run = [ "sort btime --dir-first=yes --reverse=no", "linemode btime" ],  desc = "sort: btime (dirfirst)" },
	{ on = [ ",", "B" ], run = [ "sort btime --dir-first=yes --reverse", "linemode btime" ],     desc = "rsort: btime (dirfirst)" },
	{ on = [ ",", "e" ], run = "sort extension --dir-first=yes --reverse=no",                    desc = "sort: ext (dirfirst)" },
	{ on = [ ",", "E" ], run = "sort extension --dir-first=yes --reverse",                       desc = "rsort: ext (dirfirst)" },
	{ on = [ ",", "a" ], run = "sort alphabetical --dir-first=yes --reverse=no",                 desc = "sort alphabetically (dirfirst)" },
	{ on = [ ",", "A" ], run = "sort alphabetical --dir-first=yes --reverse",                    desc = "rsort alphabetically (dirfirst)" },
	{ on = [ ",", "n" ], run = "sort natural --dir-first=yes --reverse=no",                      desc = "sort naturally (dirfirst)" },
	{ on = [ ",", "N" ], run = "sort natural --dir-first=yes --reverse",                         desc = "rsort naturally (dirfirst)" },
	{ on = [ ",", "s" ], run = [ "sort size --dir-first=yes --reverse=no", "linemode size" ],    desc = "sort: size (dirfirst)" },
	{ on = [ ",", "S" ], run = [ "sort size --dir-first=yes --reverse", "linemode size" ],       desc = "rsort: size (dirfirst)" },
	{ on = [ ",", "r" ], run = "sort random --dir-first=yes --reverse=no",                       desc = "sort: rand (dirfirst)" },
]
